---
development:
  cloud_name: anket
  api_key: '982321883659183'
  api_secret: g35HglyNhIWoVV-hqknSKbqCPKI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: anket
  api_key: '982321883659183'
  api_secret: g35HglyNhIWoVV-hqknSKbqCPKI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: anket
  api_key: '982321883659183'
  api_secret: g35HglyNhIWoVV-hqknSKbqCPKI
  enhance_image_tag: true
  static_image_support: false
